version: '3.8'

services:
  terrabyte-restapi:
    build: ./terrabyte.restapi
    ports:
      - "8082:8080"
      
  terrabyte-database:
    build: ./terrabyte.database
    environment:
      POSTGRES_PASSWORD: postgres 
      POSTGRES_USER: postgres 
      POSTGRES_DB: titans.application 
    volumes:
      - ./restore-db.sh:/docker-entrypoint-initdb.d/restore-db.sh
      - ./titans.sql:/docker-entrypoint-initdb.d/restore/dumpfile.sql
      - ./titans.data.sql:/docker-entrypoint-initdb.d/restore/dumpfile.data.sql
      #- postgres_data:/var/lib/postgresql/data
      
    ports:
      - "5433:5432"     
  