version: '3.8'

services:
  terrabyte-database:
    build: .
    container_name: terrabyte-database
    environment:
      POSTGRES_PASSWORD: postgres 
      POSTGRES_USER: postgres 
      POSTGRES_DB: titans.application 
      PROXY_ADDRESS_FORWARDING: "true"
    
    volumes:
      #- postgres_data:/var/lib/postgresql/data
      - ./restore-db.sh:/docker-entrypoint-initdb.d/restore-db.sh
      - ./titans.sql:/docker-entrypoint-initdb.d/restore/dumpfile.sql
      - ./titans.data.sql:/docker-entrypoint-initdb.d/restore/dumpfile.data.sql
    ports:
      - "5432:5432"

networks:
  default:
    external:
      name: pitch-network

